version: "2"
services:
  commafeed:
    image: heinzepreller/commafeed:latest
    ports:
      - "8082:8082"
    volumes:
      - "./commafeed-volume:/data/commafeed"
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: commafeed
      MYSQL_DATABASE: commafeed
      MYSQL_USER: commafeed
      MYSQL_PASSWORD: commafeed
